name: .NET CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - uses: actions/checkout@v4

      # 2. Setup .NET 8
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      # 3. Restore dependencies
      - name: Restore dependencies
        run: dotnet restore ./airbnb-mvp.sln

      # 4. Build solution
      - name: Build
        run: dotnet build ./airbnb-mvp.sln --no-restore --configuration Release

      # 5. Run tests
      - name: Run tests
        run: dotnet test ./backend/Airbnb.Tests/Airbnb.Tests.csproj --no-build --verbosity normal
